name: deploy-server-jar

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: echo dir
        run: dir=`pwd` && echo $dir
      - name: build
        run: mvn clean package -Dmaven.test.skip=true
